name: Publish Framework

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: 1.3.0
        
    - name: Install dependencies
      run: bun install
      
    - name: Run tests
      run: bun test tests --randomize
      env:
        CI: true
      
    - name: Build project
      run: bun run build
      
    - name: Create distribution package
      run: |
        mkdir -p dist-package
        cp -r dist dist-package/
        cp package.json dist-package/
        cp README.md dist-package/
        
        # Update package.json for distribution
        cd dist-package
        node -e "
          const pkg = JSON.parse(require('fs').readFileSync('package.json', 'utf8'));
          pkg.main = './dist/index.js';
          pkg.types = './dist/index.d.ts';
          pkg.files = ['dist/**/*', 'README.md', 'package.json'];
          pkg.scripts = {
            ...pkg.scripts,
            'prepublishOnly': 'echo \"Use GitHub releases instead of npm publish\"'
          };
          require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
        "
        
        # Create a tarball for distribution
        tar -czf ../poto.tar.gz .
        cd ..
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: Poto Framework ${{ github.event.inputs.version || github.ref_name }}
        files: |
          poto.tar.gz
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload to GitHub Packages (as artifact)
      uses: actions/upload-artifact@v4
      with:
        name: poto-${{ github.event.inputs.version || github.ref_name }}
        path: |
          poto.tar.gz
          dist-package/
        retention-days: 90
